=== platformatic/platformatic/packages/metaconfig/test/fixtures/v0.16.0/platformatic.db.schema.json
{
  "$id": "https://schemas.platformatic.dev/db",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "server": {
      "$id": "https://schemas.platformatic.dev/service/server",
      "type": "object",
      "properties": {
        "hostname": {
          "type": "string"
        },
        "port": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "string"
            }
          ]
        },
        "pluginTimeout": {
          "type": "integer"
        },
        "healthCheck": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "object",
              "properties": {
                "enabled": {
                  "type": "boolean"
                },
                "interval": {
                  "type": "integer"
                }
              },
              "additionalProperties": true
            }
          ]
        },
        "cors": {
          "type": "object",
          "$comment": "See https://github.com/fastify/fastify-cors",
          "properties": {
            "origin": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "string"
                },
                {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              ]
            },
            "methods": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "allowedHeaders": {
              "type": "string",
              "description": "Comma separated string of allowed headers."
            },
            "exposedHeaders": {
              "anyOf": [
                {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                {
                  "type": "string",
                  "description": "Comma separated string of exposed headers."
                }
              ]
            },
            "credentials": {
              "type": "boolean"
            },
            "maxAge": {
              "type": "integer"
            },
            "preflightContinue": {
              "type": "boolean",
              "default": false
            },
            "optionsSuccessStatus": {
              "type": "integer",
              "default": 204
            },
            "preflight": {
              "type": "boolean",
              "default": true
            },
            "strictPreflight": {
              "type": "boolean",
              "default": true
            },
            "hideOptionsRoute": {
              "type": "boolean",
              "default": true
            }
          },
          "additionalProperties": false
        }
      },
      "required": [
        "hostname",
        "port"
      ]
    },
    "core": {
      "$id": "https://schemas.platformatic.dev/db/core",
      "type": "object",
      "properties": {
        "connectionString": {
          "type": "string"
        },
        "schema": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "poolSize": {
          "type": "integer"
        },
        "autoTimestamp": {
          "oneOf": [
            {
              "type": "object",
              "properties": {
                "createdAt": {
                  "type": "string",
                  "default": "created_at"
                },
                "updatedAt": {
                  "type": "string",
                  "default": "updated_at"
                }
              }
            },
            {
              "type": "boolean"
            }
          ]
        },
        "graphql": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "object",
              "properties": {
                "graphiql": {
                  "type": "boolean"
                },
                "ignore": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "boolean"
                  }
                },
                "subscriptionIgnore": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          ]
        },
        "openapi": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "object",
              "properties": {
                "info": {
                  "type": "object",
                  "properties": {
                    "title": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "version": {
                      "type": "string"
                    }
                  }
                },
                "prefix": {
                  "type": "string",
                  "description": "Base URL for the OpenAPI"
                },
                "ignore": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "boolean"
                  }
                }
              },
              "additionalProperties": false
            }
          ]
        },
        "ignore": {
          "type": "object",
          "additionalProperties": {
            "type": "boolean"
          }
        },
        "limit": {
          "type": "object",
          "properties": {
            "default": {
              "type": "integer",
              "default": 10
            },
            "max": {
              "type": "integer",
              "default": 100
            }
          }
        },
        "events": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "object",
              "properties": {
                "connectionString": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          ]
        }
      },
      "required": [
        "connectionString"
      ]
    },
    "dashboard": {
      "$id": "https://schemas.platformatic.dev/db/dashboard",
      "anyOf": [
        {
          "type": "boolean"
        },
        {
          "type": "object",
          "properties": {
            "rootPath": {
              "type": "boolean",
              "description": "Whether the dashboard should be served on / path or not."
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "authorization": {
      "$id": "https://schemas.platformatic.dev/db/authorization",
      "type": "object",
      "properties": {
        "adminSecret": {
          "type": "string",
          "description": "The password should be used to login dashboard and to access routes under /_admin prefix and for admin access to REST and GraphQL endpoints with X-PLATFORMATIC-ADMIN-SECRET header."
        },
        "roleKey": {
          "type": "string",
          "description": "The user metadata key to store user roles",
          "default": "X-PLATFORMATIC-ROLE"
        },
        "anonymousRole": {
          "type": "string",
          "description": "The role name for anonymous users",
          "default": "anonymous"
        },
        "jwt": {
          "type": "object",
          "additionalProperties": true,
          "properties": {
            "secret": {
              "oneOf": [
                {
                  "type": "string",
                  "description": "the shared secret for JWT"
                },
                {
                  "type": "object",
                  "description": "the JWT secret configuration (see: https://github.com/fastify/fastify-jwt#secret-required)",
                  "additionalProperties": true
                }
              ]
            },
            "namespace": {
              "type": "string",
              "description": "the namespace for JWT custom claims"
            },
            "jwks": {
              "oneOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "object",
                  "additionalProperties": true
                }
              ]
            }
          }
        },
        "webhook": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string",
              "description": "the webhook url"
            }
          },
          "additionalProperties": false
        },
        "rules": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "role": {
                "type": "string",
                "description": "the role name to match the rule"
              },
              "entity": {
                "type": "string",
                "description": "the DB entity type to which the rule applies"
              },
              "defaults": {
                "type": "object",
                "description": "defaults for entity creation",
                "additionalProperties": {
                  "type": "string"
                }
              },
              "find": {
                "$ref": "#crud-operation-auth"
              },
              "save": {
                "$ref": "#crud-operation-auth"
              },
              "delete": {
                "$ref": "#crud-operation-auth"
              }
            },
            "required": [
              "role",
              "entity"
            ],
            "additionalProperties": false
          }
        }
      },
      "additionalProperties": false,
      "$defs": {
        "crudOperationAuth": {
          "$id": "#crud-operation-auth",
          "oneOf": [
            {
              "type": "object",
              "description": "CRUD operation authorization config",
              "properties": {
                "checks": {
                  "description": "checks for the operation",
                  "type": "object",
                  "additionalProperties": {
                    "if": {
                      "type": "object"
                    },
                    "then": {
                      "type": "object",
                      "properties": {
                        "eq": {
                          "type": "string"
                        },
                        "in": {
                          "type": "string"
                        },
                        "nin": {
                          "type": "string"
                        },
                        "nen": {
                          "type": "string"
                        },
                        "gt": {
                          "type": "string"
                        },
                        "gte": {
                          "type": "string"
                        },
                        "lt": {
                          "type": "string"
                        },
                        "lte": {
                          "type": "string"
                        }
                      },
                      "additionalProperties": false
                    },
                    "else": {
                      "type": "string"
                    }
                  }
                },
                "fields": {
                  "type": "array",
                  "description": "array of enabled field for the operation",
                  "items": {
                    "type": "string"
                  }
                }
              },
              "additionalProperties": false
            },
            {
              "type": "boolean",
              "description": "true if enabled (with not authorization constraints enabled)"
            }
          ]
        }
      }
    },
    "migrations": {
      "$id": "https://schemas.platformatic.dev/db/migrations",
      "type": "object",
      "properties": {
        "dir": {
          "type": "string",
          "description": "The path to the directory containing the migrations."
        },
        "table": {
          "type": "string"
        },
        "validateChecksums": {
          "type": "boolean"
        },
        "autoApply": {
          "type": "boolean",
          "description": "Whether to automatically apply migrations when running the migrate command."
        }
      },
      "additionalProperties": false,
      "required": [
        "dir"
      ]
    },
    "metrics": {
      "$id": "https://schemas.platformatic.dev/service/metrics",
      "anyOf": [
        {
          "type": "boolean"
        },
        {
          "type": "object",
          "properties": {
            "port": {
              "type": "integer"
            },
            "hostname": {
              "type": "string"
            },
            "auth": {
              "type": "object",
              "properties": {
                "username": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                }
              },
              "additionalProperties": false,
              "required": [
                "username",
                "password"
              ]
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "types": {
      "$id": "https://schemas.platformatic.dev/db/types",
      "type": "object",
      "properties": {
        "autogenerate": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "plugin": {
      "$id": "https://schemas.platformatic.dev/service/pluginTypes",
      "$defs": {
        "plugin": {
          "$id": "#plugin",
          "type": "object",
          "properties": {
            "path": {
              "type": "string"
            },
            "stopTimeout": {
              "type": "integer"
            },
            "typescript": {
              "type": "object",
              "properties": {
                "outDir": {
                  "type": "string"
                },
                "build": {
                  "type": "boolean",
                  "default": true
                }
              },
              "additionalProperties": false,
              "required": [
                "outDir"
              ]
            },
            "fallback": {
              "type": "boolean"
            },
            "hotReload": {
              "type": "boolean",
              "default": true
            },
            "options": {
              "type": "object"
            }
          },
          "additionalProperties": false,
          "required": [
            "path"
          ]
        }
      },
      "anyOf": [
        {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "$ref": "#plugin"
              },
              {
                "type": "string"
              }
            ]
          }
        },
        {
          "$ref": "#plugin"
        },
        {
          "type": "string"
        }
      ]
    }
  },
  "additionalProperties": {
    "watch": {
      "anyOf": [
        {
          "$id": "https://schemas.platformatic.dev/service/watch",
          "type": "object",
          "properties": {
            "type": "object",
            "properties": {
              "allow": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "minItems": 1,
                "nullable": true,
                "default": null
              },
              "ignore": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "nullable": true,
                "default": null
              }
            },
            "additionalProperties": false
          }
        },
        {
          "type": "boolean"
        }
      ]
    }
  },
  "required": [
    "core",
    "server"
  ]
}

=== platformatic/platformatic/packages/db-dashboard/test/e2e/fixtures/e2e-test-config.json
{
  "server": {
    "hostname": "127.0.0.1",
    "port": "3042",
    "logger": {
      "level": "info"
    },
    "cors": {
      "origin": true,
      "methods": [
        "GET",
        "POST",
        "PUT",
        "DELETE",
        "PATCH"
      ]
    }
  },
  "migrations": {
    "dir": "./migrations"
  },
  "core": {
    "connectionString": "postgres://postgres:postgres@127.0.0.1:5432/postgres",
    "ignore": {
      "versions": true
    }
  },
  "dashboard": {
    "rootPath": true
  },
  "authorization": {
    "adminSecret": "basegraph"
  }
}

=== platformatic/platformatic/packages/db/test/fixtures/config-to-replace.json
{
  "server": {
    "logger": {
      "level": "info"
    },
    "hostname": "127.0.0.1",
    "port": 3042
  },
  "core": {
    "connectionString": "sqlite://db.sqlite",
    "graphiql": true
  },
  "migrations": {
    "dir": "migrations"
  },
  "types": {
    "autogenerate": true
  },
  "plugin": {
    "path": "plugin"
  }
}
